### ISSUE TITLE
Cayo Perico map issue fix

### ISSUE THREAD

**Issue by AyyyBlinky** [TayMcKenzieNZ/CayoTwoIslands#2]
https://github.com/TayMcKenzieNZ/CayoTwoIslands/blob/d56bff7f14f8ab48be0eea1a43aade866e4207e9/CayoTwoIslands/scripts/twoislands.lua#L344

if #(coords - islandCoords) > 000.0 then

will then show island on map

**Comment by AyyyBlinky** [comment]
change was causing bugs to happen on main island

**Comment by TayMcKenzieNZ** [comment]
> change was causing bugs to happen on main island

Exactly why I have not implemented this "fix".

**Comment by TayMcKenzieNZ** [comment]
This does indeed make the map appear, however as you mentioned with the bugs on the main land, any interior under the map, now becomes under water.

![bug interior](https://user-images.githubusercontent.com/49776183/169641453-54384213-b4e1-4c2a-8b21-927b0cdac4ed.png)

**Comment by TayMcKenzieNZ** [comment]
It may be possible to fix it with another native

https://docs.fivem.net/natives/?_0x7E3F55ED251B76D3

**Comment by TayMcKenzieNZ** [comment]
Minimap has been fixed
