### ISSUE TITLE
texture inside hangar didn't appear

### ISSUE THREAD

**Issue by DevAlexandre0** [TayMcKenzieNZ/CayoTwoIslands#4]
when i install and start only the hangar interior not appear

**Comment by TayMcKenzieNZ** [comment]
Yeah, I'm aware. It works for some people, it doesn't for others, I do not know why.

**Comment by DevAlexandre0** [comment]
I solve it
my server have bob74_ipl
just stop it and texture will appear

**Comment by TayMcKenzieNZ** [comment]
Bob74 has nothing to do with Cayo Perico, so I do not understand

**Comment by DevAlexandre0** [comment]
My bob74_ipl is custom so I delete this line 

LoadMpDlcMaps()
EnableMpDlcMaps(true)

and it fix. bob74_ipl didn't do anythings to cayo 
may be this will help.

**Comment by TayMcKenzieNZ** [comment]
Oh, yes. That makes sense. My resources requests the IPLs for you.

Previously, the only way to have the island and hangar, was to conceal Los Santos, but I found a way around it, but I think maybe it don't work for everyone, I don't know 🤔 but I will advise other people to check IPL loaders.
