### ISSUE TITLE
How to get rid of local spawn vehicles

### ISSUE THREAD

**Issue by RebirthRP** [TayMcKenzieNZ/CayoTwoIslands#6]
I can not seem to find where to get rid of local vehicles that spawn on the map is there a fix for this issue

**Comment by TayMcKenzieNZ** [comment]
You need to use codewalker, set DLC Level to mpheist4, open CayoTwoIslands in codewalker, and delete the vehicles from the cargen ymaps.

If you don't know how codewalker works, it's time to learn as I'm not doing it for you.
