### ISSUE TITLE
City's water disappearing after being on the island

### ISSUE THREAD

**Issue by Biz96** [TayMcKenzieNZ/CayoTwoIslands#8]
Hello! I am getting a bug where all the water in Los Santos, Sandy and Paleto suddenly disappears after visiting cayo perico... any way to fix this? :D

**Comment by TayMcKenzieNZ** [comment]
Seeing as the script and everything works fine for me and others, I haven't
needed to touch it for many years / months and don't intent to.

It's possible you have another script or MLO causing this as nobody else
has the same issue as you.

I can't fix something if I can't reproduce the issue myself.
